### ISSUE TITLE
`statusBarSizeDidChange` is not a supported event type for RCTStatusBarManager

### ISSUE THREAD

**Issue by limulidae** [brentvatne/react-native-status-bar-size#10]
with RN 0.27.2

**Comment by limulidae** [comment]
one time I successfully get height=20,
most of the time it has this failure.

**Comment by npomfret** [comment]
Anyone got a workaround?

**Comment by tioback** [comment]
Check out [livecirrus' fork](https://github.com/livecirrus/react-native-status-bar-size).

**Comment by npomfret** [comment]
Works like charm.  Any chance of getting the change put into here?

**Comment by tioback** [comment]
I added pull request #11 a few days ago, but @brentvatne must be busy or something.

**Comment by janmarsicek** [comment]
@tioback @npomfret I get the same error and wasn't able to make it work with RN 0.30 😒  renaming event types to `statusBarFrameWillChange` and `statusBarFrameDidChange` did the trick. Check out [my fork](https://github.com/janmarsicek/react-native-status-bar-size/pull/2/commits/f095e5aeed49a9d0ad65f906474d56f036924c25)

**Comment by nverdhan** [comment]
This should be resolved by PR #14.

**Comment by jgkim** [comment]
I guess this package no longer suffers from this issue.
