### ISSUE TITLE
libRNStatusBarSize.a not found

### ISSUE THREAD

**Issue by good2hear** [brentvatne/react-native-status-bar-size#16]
Hi there,
I'm trying to get the iOS status bar height using this package
but then I'm not able to find and add libRNStatusBarSize.a file in my xcode after npm install 
what am I missing?

any comments will be appreciated!

**Comment by darye** [comment]
I just took the project file and dragged it in to the Libraries folder in Xcode, that worked for me.

**Comment by jgkim** [comment]
This package no longer contains `libRNStatusBarSize.a`.
