### ISSUE TITLE
DeviceEventEmitter issue - is the latest code on npm?

### ISSUE THREAD

**Issue by liron00** [brentvatne/react-native-status-bar-size#5]
I installed from npm and had to change "RCTDeviceEventEmitter" to "DeviceEventEmitter" in a couple places in your code to make this work. Does npm have the latest version?

**Comment by TheWildHorse** [comment]
Yes, the current version on NPM is giving this error, but the files in the repo look fine.

@brentvatne Please publish the new version on NPM. Thank you!

**Comment by brentvatne** [comment]
OK I published the new version to npm, 0.2.1, hope that fixes it! I don't use this library right now so if either of you wants to manage it, I will happily add you to npm and as an owner of this repo!
