### ISSUE TITLE
Weird use of types is causing a Flow error

### ISSUE THREAD

**Issue by liron00** [brentvatne/react-native-status-bar-size#7]
On this line - https://github.com/brentvatne/react-native-status-bar-size/blob/master/StatusBarSizeIOS.js#L88

You're using a Function type as the key to index into an object. Is this a mistake?

I'm surprised you guys have `// @flow` at the top of the file, because Flow would have caught the issue for you. At the moment, Flow insists on checking your module as part of my project, and I have no way to even stifle the Flow error short of forking your package.

**Comment by ckknight** [comment]
This is definitely a bug. Functions should not be object keys. It'll lead to strange conflicts if two functions return the same value from `[[ToString]]`.

**Comment by ckknight** [comment]
Fixed via https://github.com/jgkim/react-native-status-bar-size/pull/17
